# permissions for end users to edit emailers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: emailer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: banshee-operator
    app.kubernetes.io/part-of: banshee-operator
    app.kubernetes.io/managed-by: kustomize
  name: emailer-editor-role
rules:
- apiGroups:
  - github.com
  resources:
  - emailers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.com
  resources:
  - emailers/status
  verbs:
  - get
